export const INITIATE_PRODUCTS = 'INITIATE_PRODUCTS'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS'
export const TOGGLE_FILTER_OVERLAY = 'TOGGLE_FILTER_OVERLAY'
export const TOGGLE_IMAGE_OVERLAY = 'TOGGLE_IMAGE_OVERLAY'